name: Deploy to AWS Lambda

on:
  push:
    branches:
      - go-lambda

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::759663378274:role/github_actions_oidc
          aws-region: eu-west-1
          audience: sts.amazonaws.com

      - name: Build the Go application
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go

      - name: Package the application
        run: |
          zip bootstrap.zip bootstrap

      - name: Deploy Lambdas and Setup API Gateway
        run: |
          FUNCTION_NAME="api"
          API_ID="bg4yv0rzhe"
          REGION="eu-west-1"
          ZIP_FILE="bootstrap.zip"
          ROLE_ARN="arn:aws:iam::759663378274:role/service-role/api-role-pydrwpue"


          # Deploy Lambda function
          aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://$ZIP_FILE

          # Wait for the function update to complete before proceeding
          aws lambda wait function-updated --function-name $FUNCTION_NAME

          # Update Lambda environment variables
          aws lambda update-function-configuration \
            --function-name $FUNCTION_NAME \
            --environment "Variables={JWT_SECRET='$JWT_SECRET'}"
